apiVersion: v1
kind: Service
metadata:
  name: {{ include "elune-aio.fullname" . }}
  labels:
    {{- include "elune-aio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "elune-aio.selectorLabels" . | nindent 4 }}
